theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: "guides"
      type: "pages"
    values:
      isguide: true
guides:
  -
    path: "/guides/getting-started"
    title: "Getting started"
  -
    path: "/guides/annotations"
    title: "Annotations"
  -
    path: "/guides/dynamic-resources"
    title: "Dynamic resources"
  -
    path: "/guides/validation"
    title: "Validation"
  -
    path: "/guides/form-elements"
    title: "Form Elements"
  -
    path: "/guides/actions"
    title: "Actions"
  -
    path: "/guides/environments"
    title: "Environments"
  -
    path: "/guides/xml"
    title: "XML Forms"